SElECT * FROM customers ;
/* Identify different customer segments based on their demographic and behavoural characteristics */

SELECT AGE,GENDER,
COUNT(*) AS CUSTOMERS_COUNT FROM
customers
group by age ,gender;
SELECT CASE
WHEN INCOME < 40000 THEN 'LOW INCOME'
WHEN INCOME BETWEEN 40000 AND 50000 THEN 'MIDDLE INCOME'
WHEN INCOME> 50000 THEN 'HIGH INCOME '
END AS INCOME_SEGMENT,
COUNT(*)AS CUSTOMER_COUNT
FROM customers
GROUP BY INCOME;

SELECT MAX(INCOME)
FROM customers;
SELECT CASE
WHEN SPENDING_SCORE < 20 THEN 'LOW SPENDING'
WHEN SPENDING_SCORE BETWEEN 20 AND 50 THEN ' MEDIUM SPENDING '
WHEN SPENDING_SCORE > 50 THEN 'HIGH SPENDING '
END AS SPENDING_SEGMENT ,
COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY SPENDING_SCORE ;
SELECT 
CASE 
WHEN MEMBERSHIP_YEARS < 2 THEN 'NEW MEMBER'
WHEN MEMBERSHIP_YEARS BETWEEN 2 AND 6 THEN 'REGULAR MEMBER '
WHEN MEMBERSHIP_YEARS > 6 THEN 'LONG TERM MEMBER '
END AS MEMBERSHIP_SEGMENT ,
COUNT(*) AS CUSTOMER_COUNT
FROM customers
GROUP BY
MEMBERSHIP_YEARS ;
SELECT CASE
WHEN PURCHASE_FREQUENCY < 5 THEN 'INFREQUENT BUYER '
WHEN PURCHASE_FREQUENCY BETWEEN 5 AND 20 THEN 'REGUALR BUYER '
WHEN PURCHASE_FREQUENCY > 20 THEN 'FREQUENT BUYER'
END FREQUENCY_SEGMENT ,
COUNT(*)AS CUSTOMER_COUNT
FROM customers
GROUP BY
PURCHASE_FREQUENCY ;

SELECT PREFFERED_CATEGORY,
COUNT(*) AS CUSTOMER_COUNT
FROM customers 
GROUP BY 
PREFFERED_CATEGORY;








